<!DOCTYPE html>
<html>
	<head>
		<title>
			Demonstrating Exception handling in JS
		</title>
	</head>
	<body>
		<script type="text/javascript">
			console.log("hello everyone");
			var a = 90;
			var b = 30;
			var result = a + b;
			try{
				document.querySelector("#abc").innerHTML = "hello";	//here "abc" id is not there so it throws error so we need to handle this error.
				console.log("after the code");
			} catch(err) {
				console.log("there is an error(exception) handled");
			}
			console.log("the sum is : " + result);
			console.log("done with this coding");
		</script>
	</body>
</html>